# Generated by Django 3.2.4 on 2021-07-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_requesttocourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('id_course', models.IntegerField()),
            ],
        ),
    ]
