# Generated by Django 3.2.4 on 2021-07-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link_to_materials',
            field=models.CharField(default='https://disk.yandex.ru/d/Peol1rVjZTEjrA', max_length=500, null=True),
        ),
    ]
