# Generated by Django 3.2.4 on 2021-07-29 08:37

from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_link_to_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schedule_number',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.IntegerField()),
                ('day', models.IntegerField(validators=[school.models.validate_day])),
                ('time', models.TimeField()),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.course')),
            ],
        ),
    ]
