# Generated by Django 3.2.4 on 2021-07-29 15:45

from django.db import migrations, models
import django.db.models.deletion
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20210729_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('telegram', models.CharField(max_length=100, null=True)),
                ('mail', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100, validators=[school.validators.validate_phone])),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['time', 'day']},
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.teachers'),
        ),
    ]
